### ISSUE TITLE
Tables with Schemas having problems in v4 templates

### ISSUE THREAD

**Issue by lhughey** [mattjcowan/LLBLGenPro_SS_Api_Razor_Templates#5]
Matt, first I would like to thank you for such great templates.  They are extremely helpful. 

I'm having a problem with tables (entities) that are a part of a schema are not having their schema prefix persisted to the DB call.

I have an adventureworks table where the customers table belongs to a schema other than dbo.  When I use the entity browser and navigate to the customer entitiy page,  no records are returned.  I traced the result back to the fact that the schema is not being carried to the call to the database.  The final query sent to the DB is   "SELECT COUNT(*) AS [LPAV_] FROM [Customer]", and results in a SQL "Invalid object name 'Customer'.  I was able to verify the remedy by inserting a synonym for the table to map my schema to the schema of dbo.

Thanks again for this wonderful project.

**Comment by mattjcowan** [comment]
I didn't have multiple schemas in mind as a use-case with these templates, but with some slight changes I would imagine it could be made to work.

Have you tried playing around with your project's IDataAccessAdapterFactory implementation? I believe in the sample I just [clear out the schema](https://github.com/mattjcowan/LLBLGenPro_SS_Api_Razor_Templates/blob/008059eb00e51aced12aa658c8c22a34b68b290b/src_v4/Hosts/ConsoleHost/Program.cs#L208) (keeping it simple) when doing "new DataAccessAdapter()"... Maybe try some variations on newing up the data access adapter to include the schema in llblgen queries. I'm not guaranteeing that will work (might have some unforeseen side-effects since I haven't tested this use-case yet) but would be the place to start probably. If you try that out, let me know if it doesn't work.

**Comment by lhughey** [comment]
Thanks for the quick response, Matt.  A simple change to the IDataAccessAdapterFactory resolved the issue I was having.  Thanks again for these templates.  They are great.
